const cartActionTypes = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    CLEAR_ITEM: "CLEAR_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    ADD_COURSEITEM: "ADD_COURSEITEM",
    CLEAR_COURSEITEM: "CLEAR_COURSEITEM",
    REMOVE_COURSEITEM: "REMOVE_COURSEITEM",
    SET_ORDERINFO: "SET_ORDERINFO",
    CLEAR_ALL: "CLEAR_ALL"

}



export default cartActionTypes;